### PR TITLE
Dynamic width for the tabs than fixed.

### PR DESCRIPTION
**Pull request by abingeorgev**
Update for auto width than fixed width. Just use segment.fixedWidth = false after initialization.

### CODE REVIEW

**Comment by mbappinte** [comment]
Is it possible that it also takes into account the size of the image when the segmentStyle is `imageLeft` ?
And then make a new release ?

**Comment by abingeorgev** [comment]
Okay let me check.

**Comment by AbidHussainCom** [comment]
How can I access this branch? I need it ASAP.

**Comment by abingeorgev** [comment]
@bleformal I have fixed the dynamic width for image left and image only. 
@AbidHussainCom Please wait until @bleformal bleformal merges it. Or else, please use my fork for now.

https://github.com/abingeorgev/ScrollableSegmentedControl

**Comment by GocePetrovski** [comment]
I'm closing this pull request because I found a cleaner way of implementing this functionality. Please see the master branch.

**Pull request closed without merging**
